### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by NickHam13** [lamaprogramer/midnightlurker#1]
[00:12:00] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "midnightlurker:midnightlurker"
java.lang.NullPointerException: Cannot invoke "net.mcreator.midnightlurker.util.IEntityDataSaver.getPersistentData()" because "variables" is null

Fabric 1.20.1. I can provide more details or full logs if needed

**Comment by lamaprogramer** [comment]
Should be fixed now, version 1.0.1 should be out on modrinth, but gotta wait on curseforge to approve it.
