### ISSUE TITLE
Bug on fabric server when connection

### ISSUE THREAD

**Issue by furax124** [lamaprogramer/midnightlurker#2]
Hello when i connect to my fabric server it crashed with midnight mod here crash log
[crash-2024-04-07_12.53.49-server.txt](https://github.com/lamaprogramer/midnightlurker/files/14896861/crash-2024-04-07_12.53.49-server.txt)

**Comment by lamaprogramer** [comment]
Sorry it took a sec, this should be fixed in the latest version!
